context.modules = [

    #
    # WebRTC Echo Cancel
    #
    {
        name = libpipewire-module-echo-cancel
        args = {
            monitor.mode = true

            capture.props = {
                node.passive = true
            }

            source.props = {
                node.name = "source_ec"
                node.description = "Echo Cancel Source"
            }

            aec.method = "webrtc"

            aec.args = {
                webrtc.extended_filter = false
                webrtc.delay_agnostic = true

                webrtc.noise_suppression = false

                webrtc.high_pass_filter = true
                webrtc.gain_control = false
                webrtc.voice_detection = false
            }
        }
    },

    #
    # RNNoise Filter
    #
    {
        name = libpipewire-module-filter-chain
        args = {
            node.description = "Clean Mic"
            media.name = "Clean Mic"

            filter.graph = {
                nodes = [
                    {
                        type = ladspa
                        name = rnnoise
                        plugin = /usr/lib/ladspa/librnnoise_ladspa.so
                        label = noise_suppressor_mono

                        control = {
                            "VAD Threshold (%)" 50.0
                            "VAD Grace Period (ms)" 200
                            "Retroactive VAD Grace (ms)" 0
                        }
                    }
                ]
            }

            capture.props = {
                node.name = "capture.rnnoise"
                node.target = "source_ec"
                node.passive = true
            }

            playback.props = {
                media.class = "Audio/Source"
                node.name = "clean_mic"
                node.description = "Clean Mic"
            }
        }
    }
]
